app:
    resource: @AppBundle/Controller/
    type:     annotation

acme_api:
    type: rest
    prefix: /api
    resource: "@AcmeApiBundle/Resources/config/routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc